"""update models fields & relationships

Revision ID: 03e7f83d7d80
Revises: 750fe3786620
Create Date: 2026-02-23 09:38:07.392313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03e7f83d7d80'
down_revision: Union[str, Sequence[str], None] = '750fe3786620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('source_file_url', sa.String(length=500), nullable=True, comment='Cloudinary secure_url of the uploaded claim file'))
    op.add_column('claims', sa.Column('source_file_public_id', sa.String(length=255), nullable=True, comment='Cloudinary public_id — used to delete or replace the file'))
    op.add_column('claims', sa.Column('provider_name', sa.String(length=255), nullable=True, comment='Name of Health Care Provider/Facility (Form Field 2)'))
    op.add_column('claims', sa.Column('patient_last_name', sa.String(length=100), nullable=True))
    op.add_column('claims', sa.Column('patient_first_name', sa.String(length=100), nullable=True))
    op.add_column('claims', sa.Column('patient_middle_name', sa.String(length=100), nullable=True))
    op.add_column('claims', sa.Column('patient_residence', sa.String(length=255), nullable=True, comment='Residence (Form Field 5)'))
    op.add_column('claims', sa.Column('other_insurance', sa.String(length=255), nullable=True, comment='Other health insurance if any (Form Field 6)'))
    op.add_column('claims', sa.Column('relationship_to_principal', sa.String(length=100), nullable=True, comment='Relationship to Principal (Form Field 7)'))
    op.add_column('claims', sa.Column('was_referred', sa.Boolean(), nullable=True, comment='Whether patient was referred by another provider (Form Field 7)'))
    op.add_column('claims', sa.Column('referral_provider', sa.String(length=255), nullable=True, comment='Name of referring Health Care Provider/Facility'))
    op.add_column('claims', sa.Column('new_or_return_visit', sa.String(length=20), nullable=True, comment='New | Return (Form Part III)'))
    op.add_column('claims', sa.Column('rendering_physician', sa.String(length=300), nullable=True, comment='Rendering Physician Name and Registration No. (combined, Form Part III)'))
    op.add_column('claims', sa.Column('discharge_referral_institution', sa.String(length=255), nullable=True, comment='Name of Referral Institution on discharge (Form Field 10)'))
    op.add_column('claims', sa.Column('discharge_referral_reason', sa.Text(), nullable=True, comment='Reason/s for discharge referral (Form Field 10)'))
    op.add_column('claims', sa.Column('icd11_code', sa.String(length=50), nullable=True, comment='ICD-11 Code/s (Form Field 12)'))
    op.add_column('claims', sa.Column('related_procedure', sa.Text(), nullable=True, comment='Related Procedure/s if any (Form Field 12)'))
    op.add_column('claims', sa.Column('procedure_date', sa.DateTime(), nullable=True, comment='Date of Procedure (Form Field 12)'))
    op.add_column('claims', sa.Column('benefit_lines', sa.JSON(), nullable=True, comment='SHA Health Benefits table rows (Form Field 14)'))
    op.add_column('claims', sa.Column('total_bill_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Sum of bill_amount across all benefit lines'))
    op.add_column('claims', sa.Column('total_claim_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Sum of claim_amount across all benefit lines'))
    op.add_column('claims', sa.Column('patient_authorised_name', sa.String(length=300), nullable=True, comment='Names (Majina) from patient/authorised person declaration'))
    op.add_column('claims', sa.Column('declaration_date', sa.DateTime(), nullable=True, comment='Date (Tarehe) from patient declaration'))
    op.add_column('claims', sa.Column('submitted_by', sa.UUID(), nullable=True, comment='User who submitted the claim via the API'))
    op.alter_column('claims', 'provider_code',
               existing_type=sa.VARCHAR(length=50),
               comment='SHA Provider Identification Number (Form Field 1)',
               existing_nullable=True)
    op.alter_column('claims', 'patient_sha_number',
               existing_type=sa.VARCHAR(length=50),
               comment='Social Health Authority Number (Form Field 4) — primary patient identifier',
               existing_nullable=True)
    op.alter_column('claims', 'patient_full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('claims', 'visit_type',
               existing_type=postgresql.ENUM('INPATIENT', 'OUTPATIENT', 'DAYCARE', name='visittype'),
               comment='Inpatient | Outpatient | Day-care',
               existing_nullable=True)
    op.alter_column('claims', 'visit_admission_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Visit/Admission Date — primary date field; service_date is removed',
               existing_nullable=True)
    op.alter_column('claims', 'op_ip_number',
               existing_type=sa.VARCHAR(length=50),
               comment='OP/IP Number',
               existing_nullable=True)
    op.alter_column('claims', 'patient_disposition',
               existing_type=postgresql.ENUM('IMPROVED', 'RECOVERED', 'LAMA', 'ABSCONDED', 'DIED', name='patientdisposition'),
               comment='Improved | Recovered | LAMA | Absconded | Died (Form Field 9)',
               existing_nullable=True)
    op.alter_column('claims', 'admission_diagnosis',
               existing_type=sa.TEXT(),
               comment='Admission Diagnosis/es (Form Field 11)',
               existing_nullable=True)
    op.alter_column('claims', 'discharge_diagnosis',
               existing_type=sa.TEXT(),
               comment='Discharge Diagnosis (Form Field 12)',
               existing_nullable=True)
    op.alter_column('claims', 'fraud_flags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Array of fraud flag dicts from detection modules',
               existing_nullable=True)
    op.drop_index(op.f('ix_claims_patient_national_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_service_date'), table_name='claims')
    op.create_index(op.f('ix_claims_total_claim_amount'), 'claims', ['total_claim_amount'], unique=False)
    op.create_foreign_key(None, 'claims', 'users', ['submitted_by'], ['id'])
    op.drop_column('claims', 'patient_national_id')
    op.drop_column('claims', 'original_file_type')
    op.drop_column('claims', 'claim_amount')
    op.drop_column('claims', 'procedures')
    op.drop_column('claims', 'service_date')
    op.drop_column('claims', 'supporting_documents')
    op.drop_column('claims', 'rendering_physician_name')
    op.drop_column('claims', 'admission_diagnosis_codes')
    op.drop_column('claims', 'referring_facility')
    op.drop_column('claims', 'referral_out_reason')
    op.drop_column('claims', 'is_new_visit')
    op.drop_column('claims', 'original_file_path')
    op.drop_column('claims', 'referred_to_facility')
    op.drop_column('claims', 'is_referred')
    op.drop_column('claims', 'discharge_diagnosis_codes')
    op.drop_column('claims', 'rendering_physician_reg_no')
    op.drop_column('claims', 'referral_reason')
    op.add_column('patients', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('relationship_to_principal', sa.String(length=50), nullable=True, comment='Principal | Spouse | Child | Dependant'))
    op.add_column('patients', sa.Column('sha_verified', sa.Boolean(), nullable=False, comment='True if SHA registry confirmed this member exists and is active'))
    op.add_column('patients', sa.Column('sha_verified_at', sa.DateTime(), nullable=True, comment='Timestamp of last successful SHA registry verification'))
    op.add_column('patients', sa.Column('sha_registry_response', sa.Text(), nullable=True, comment='Last raw JSON response from SHA registry (audit trail)'))
    op.add_column('patients', sa.Column('last_claim_date', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('total_claims_count', sa.Integer(), nullable=False))
    op.alter_column('patients', 'sha_number',
               existing_type=sa.VARCHAR(length=50),
               comment='SHA Membership Number — primary identifier on the 2023 claim form',
               existing_nullable=True)
    op.alter_column('patients', 'national_id_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256 hash of National ID — legacy field, not on SHA 2023 form',
               existing_nullable=True)
    op.alter_column('patients', 'age_group',
               existing_type=sa.VARCHAR(length=20),
               comment='0-5 | 6-18 | 19-35 | 36-50 | 51-65 | 66+',
               existing_nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(length=10),
               comment='M | F — used by PhantomPatientDetector medical plausibility check',
               existing_nullable=True)
    op.alter_column('patients', 'county',
               existing_type=sa.VARCHAR(length=100),
               comment='Home county — used for geographic impossibility cross-check',
               existing_nullable=True)
    op.alter_column('patients', 'death_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Set when SHA registry confirms member is deceased',
               existing_nullable=True)
    op.create_index(op.f('ix_patients_is_deceased'), 'patients', ['is_deceased'], unique=False)
    op.create_index(op.f('ix_patients_last_claim_date'), 'patients', ['last_claim_date'], unique=False)
    op.drop_column('patients', 'iprs_verified_at')
    op.drop_column('patients', 'is_verified')
    op.add_column('providers', sa.Column('provider_id', sa.String(length=50), nullable=False, comment='SHA Provider Identification Number — Form Field 1'))
    op.add_column('providers', sa.Column('total_billed_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Sum of total_bill_amount across all claims'))
    op.add_column('providers', sa.Column('total_claimed_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Sum of total_claim_amount across all claims'))
    op.add_column('providers', sa.Column('average_claimed_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Rolling average of total_claim_amount'))
    op.add_column('providers', sa.Column('is_suspended', sa.Boolean(), nullable=False))
    op.add_column('providers', sa.Column('suspension_reason', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('suspended_at', sa.DateTime(), nullable=True))
    op.add_column('providers', sa.Column('last_claim_date', sa.DateTime(), nullable=True))
    op.alter_column('providers', 'provider_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='Internal provider code (legacy/display use only)')
    op.alter_column('providers', 'facility_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Level 2 | Level 3 | Level 4 | Level 5 | Private Hospital | Clinic',
               existing_nullable=True)
    op.alter_column('providers', 'county',
               existing_type=sa.VARCHAR(length=100),
               comment='Used by PhantomPatientDetector for geographic impossibility checks',
               existing_nullable=True)
    op.alter_column('providers', 'capacity',
               existing_type=sa.INTEGER(),
               comment='Number of beds',
               existing_nullable=True)
    op.alter_column('providers', 'accreditation_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Accredited | Pending | Suspended',
               existing_nullable=True)
    op.alter_column('providers', 'sha_contract_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Active | Suspended | Terminated',
               existing_nullable=True)
    op.alter_column('providers', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               comment='CRITICAL | HIGH | MEDIUM | LOW — read by ProviderProfiler',
               existing_nullable=True)
    op.drop_index(op.f('ix_providers_provider_id_number'), table_name='providers')
    op.create_index(op.f('ix_providers_is_active'), 'providers', ['is_active'], unique=False)
    op.create_index(op.f('ix_providers_is_blacklisted'), 'providers', ['is_blacklisted'], unique=False)
    op.create_index(op.f('ix_providers_last_claim_date'), 'providers', ['last_claim_date'], unique=False)
    op.create_index(op.f('ix_providers_provider_id'), 'providers', ['provider_id'], unique=True)
    op.create_index(op.f('ix_providers_risk_level'), 'providers', ['risk_level'], unique=False)
    op.create_index(op.f('ix_providers_risk_score'), 'providers', ['risk_score'], unique=False)
    op.drop_column('providers', 'average_claim_amount')
    op.drop_column('providers', 'provider_id_number')
    op.drop_column('providers', 'total_claims_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('total_claims_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('providers', sa.Column('provider_id_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('providers', sa.Column('average_claim_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_providers_risk_score'), table_name='providers')
    op.drop_index(op.f('ix_providers_risk_level'), table_name='providers')
    op.drop_index(op.f('ix_providers_provider_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_last_claim_date'), table_name='providers')
    op.drop_index(op.f('ix_providers_is_blacklisted'), table_name='providers')
    op.drop_index(op.f('ix_providers_is_active'), table_name='providers')
    op.create_index(op.f('ix_providers_provider_id_number'), 'providers', ['provider_id_number'], unique=True)
    op.alter_column('providers', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='CRITICAL | HIGH | MEDIUM | LOW — read by ProviderProfiler',
               existing_nullable=True)
    op.alter_column('providers', 'sha_contract_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Active | Suspended | Terminated',
               existing_nullable=True)
    op.alter_column('providers', 'accreditation_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Accredited | Pending | Suspended',
               existing_nullable=True)
    op.alter_column('providers', 'capacity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of beds',
               existing_nullable=True)
    op.alter_column('providers', 'county',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Used by PhantomPatientDetector for geographic impossibility checks',
               existing_nullable=True)
    op.alter_column('providers', 'facility_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Level 2 | Level 3 | Level 4 | Level 5 | Private Hospital | Clinic',
               existing_nullable=True)
    op.alter_column('providers', 'provider_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment=None,
               existing_comment='Internal provider code (legacy/display use only)')
    op.drop_column('providers', 'last_claim_date')
    op.drop_column('providers', 'suspended_at')
    op.drop_column('providers', 'suspension_reason')
    op.drop_column('providers', 'is_suspended')
    op.drop_column('providers', 'average_claimed_amount')
    op.drop_column('providers', 'total_claimed_amount')
    op.drop_column('providers', 'total_billed_amount')
    op.drop_column('providers', 'provider_id')
    op.add_column('patients', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('iprs_verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_patients_last_claim_date'), table_name='patients')
    op.drop_index(op.f('ix_patients_is_deceased'), table_name='patients')
    op.alter_column('patients', 'death_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Set when SHA registry confirms member is deceased',
               existing_nullable=True)
    op.alter_column('patients', 'county',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Home county — used for geographic impossibility cross-check',
               existing_nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='M | F — used by PhantomPatientDetector medical plausibility check',
               existing_nullable=True)
    op.alter_column('patients', 'age_group',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='0-5 | 6-18 | 19-35 | 36-50 | 51-65 | 66+',
               existing_nullable=True)
    op.alter_column('patients', 'national_id_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA-256 hash of National ID — legacy field, not on SHA 2023 form',
               existing_nullable=True)
    op.alter_column('patients', 'sha_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='SHA Membership Number — primary identifier on the 2023 claim form',
               existing_nullable=True)
    op.drop_column('patients', 'total_claims_count')
    op.drop_column('patients', 'last_claim_date')
    op.drop_column('patients', 'sha_registry_response')
    op.drop_column('patients', 'sha_verified_at')
    op.drop_column('patients', 'sha_verified')
    op.drop_column('patients', 'relationship_to_principal')
    op.drop_column('patients', 'middle_name')
    op.drop_column('patients', 'first_name')
    op.drop_column('patients', 'last_name')
    op.add_column('claims', sa.Column('referral_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('rendering_physician_reg_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('discharge_diagnosis_codes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('is_referred', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('claims', sa.Column('referred_to_facility', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('original_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('is_new_visit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('referral_out_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('referring_facility', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('admission_diagnosis_codes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('rendering_physician_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('supporting_documents', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('service_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('claims', sa.Column('procedures', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('claim_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('claims', sa.Column('original_file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('claims', sa.Column('patient_national_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_index(op.f('ix_claims_total_claim_amount'), table_name='claims')
    op.create_index(op.f('ix_claims_service_date'), 'claims', ['service_date'], unique=False)
    op.create_index(op.f('ix_claims_patient_national_id'), 'claims', ['patient_national_id'], unique=False)
    op.alter_column('claims', 'fraud_flags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Array of fraud flag dicts from detection modules',
               existing_nullable=True)
    op.alter_column('claims', 'discharge_diagnosis',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Discharge Diagnosis (Form Field 12)',
               existing_nullable=True)
    op.alter_column('claims', 'admission_diagnosis',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Admission Diagnosis/es (Form Field 11)',
               existing_nullable=True)
    op.alter_column('claims', 'patient_disposition',
               existing_type=postgresql.ENUM('IMPROVED', 'RECOVERED', 'LAMA', 'ABSCONDED', 'DIED', name='patientdisposition'),
               comment=None,
               existing_comment='Improved | Recovered | LAMA | Absconded | Died (Form Field 9)',
               existing_nullable=True)
    op.alter_column('claims', 'op_ip_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='OP/IP Number',
               existing_nullable=True)
    op.alter_column('claims', 'visit_admission_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Visit/Admission Date — primary date field; service_date is removed',
               existing_nullable=True)
    op.alter_column('claims', 'visit_type',
               existing_type=postgresql.ENUM('INPATIENT', 'OUTPATIENT', 'DAYCARE', name='visittype'),
               comment=None,
               existing_comment='Inpatient | Outpatient | Day-care',
               existing_nullable=True)
    op.alter_column('claims', 'patient_full_name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('claims', 'patient_sha_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Social Health Authority Number (Form Field 4) — primary patient identifier',
               existing_nullable=True)
    op.alter_column('claims', 'provider_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='SHA Provider Identification Number (Form Field 1)',
               existing_nullable=True)
    op.drop_column('claims', 'submitted_by')
    op.drop_column('claims', 'declaration_date')
    op.drop_column('claims', 'patient_authorised_name')
    op.drop_column('claims', 'total_claim_amount')
    op.drop_column('claims', 'total_bill_amount')
    op.drop_column('claims', 'benefit_lines')
    op.drop_column('claims', 'procedure_date')
    op.drop_column('claims', 'related_procedure')
    op.drop_column('claims', 'icd11_code')
    op.drop_column('claims', 'discharge_referral_reason')
    op.drop_column('claims', 'discharge_referral_institution')
    op.drop_column('claims', 'rendering_physician')
    op.drop_column('claims', 'new_or_return_visit')
    op.drop_column('claims', 'referral_provider')
    op.drop_column('claims', 'was_referred')
    op.drop_column('claims', 'relationship_to_principal')
    op.drop_column('claims', 'other_insurance')
    op.drop_column('claims', 'patient_residence')
    op.drop_column('claims', 'patient_middle_name')
    op.drop_column('claims', 'patient_first_name')
    op.drop_column('claims', 'patient_last_name')
    op.drop_column('claims', 'provider_name')
    op.drop_column('claims', 'source_file_public_id')
    op.drop_column('claims', 'source_file_url')
    # ### end Alembic commands ###
