"""add case_number to fraud_cases

Revision ID: 30f15b2003b4
Revises: bb1fb610df58
Create Date: 2026-03-05 11:26:19.288810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30f15b2003b4'
down_revision: Union[str, Sequence[str], None] = 'bb1fb610df58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fraud_cases', sa.Column('case_number', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('fraud_cases', sa.Column('findings', sa.Text(), nullable=True, comment='Analyst findings narrative'))
    op.add_column('fraud_cases', sa.Column('progress', sa.Integer(), nullable=False, comment='Investigation progress 0–100%'))
    op.add_column('fraud_cases', sa.Column('target_date', sa.DateTime(timezone=True), nullable=True, comment='Target completion date'))
    op.add_column('fraud_cases', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Evidence files: [{"id":..,"file_name":..,"file_type":..,"file_url":..,"uploaded_by":..,"uploaded_at":..}]'))
    op.create_unique_constraint(None, 'fraud_cases', ['case_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fraud_cases', type_='unique')
    op.drop_column('fraud_cases', 'evidence')
    op.drop_column('fraud_cases', 'target_date')
    op.drop_column('fraud_cases', 'progress')
    op.drop_column('fraud_cases', 'findings')
    op.drop_column('fraud_cases', 'case_number')
    # ### end Alembic commands ###
