"""add fraud_reports table

Revision ID: 4c335c9afac5
Revises: 8044be774367
Create Date: 2026-03-16 16:27:07.912858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c335c9afac5'
down_revision: Union[str, Sequence[str], None] = '8044be774367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment="User-provided report name, e.g. 'Weekly Fraud Summary'"),
    sa.Column('report_type', sa.String(length=50), nullable=False, comment='summary | provider | investigation | county'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='processing | completed | scheduled | failed'),
    sa.Column('date_range_preset', sa.String(length=20), nullable=True, comment='week | month | quarter | year | custom'),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True, comment='Start of the analysis window'),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True, comment='End of the analysis window'),
    sa.Column('period_label', sa.String(length=100), nullable=True, comment="Human-readable period shown in the table, e.g. '2024-02-05 to 2024-02-11'"),
    sa.Column('record_count', sa.Integer(), nullable=False, comment='Number of claims/records analysed'),
    sa.Column('summary_text', sa.Text(), nullable=True, comment='Auto-generated narrative shown in the Report Summary card'),
    sa.Column('custom_notes', sa.Text(), nullable=True, comment='Optional analyst notes entered in the Generate dialog'),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='\n        Computed metrics stored as JSONB:\n        {\n          "fraud_detection_rate": 12.0,\n          "fraud_amount_detected": 63195.112,\n          "alert_cases_generated": 91,\n          "type_specific": {}\n        }\n        '),
    sa.Column('download_url', sa.String(length=500), nullable=True, comment='Storage URL for the generated report file (PDF/CSV/JSON)'),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False, comment='When generation was triggered (shown in Generated column)'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When the report finished processing'),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_reports_report_type'), 'fraud_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_fraud_reports_status'), 'fraud_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_reports_status'), table_name='fraud_reports')
    op.drop_index(op.f('ix_fraud_reports_report_type'), table_name='fraud_reports')
    op.drop_table('fraud_reports')
    # ### end Alembic commands ###
