"""fix user claim relationship error

Revision ID: 750fe3786620
Revises: 91869c8cce95
Create Date: 2026-02-17 09:16:45.970105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750fe3786620'
down_revision: Union[str, Sequence[str], None] = '91869c8cce95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'audit_logs', ['id'])
    op.create_unique_constraint(None, 'claims', ['id'])
    op.create_unique_constraint(None, 'fraud_alerts', ['id'])
    op.create_unique_constraint(None, 'investigations', ['id'])
    op.create_unique_constraint(None, 'ml_models', ['id'])
    op.create_unique_constraint(None, 'patients', ['id'])
    op.create_unique_constraint(None, 'providers', ['id'])
    op.create_unique_constraint(None, 'system_metrics', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'system_metrics', type_='unique')
    op.drop_constraint(None, 'providers', type_='unique')
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_constraint(None, 'ml_models', type_='unique')
    op.drop_constraint(None, 'investigations', type_='unique')
    op.drop_constraint(None, 'fraud_alerts', type_='unique')
    op.drop_constraint(None, 'claims', type_='unique')
    op.drop_constraint(None, 'audit_logs', type_='unique')
    # ### end Alembic commands ###
