"""add submitted_hour and eligibility_checked to claim_feature

Revision ID: 88ad7cb7b7e9
Revises: b6f9f417bd0a
Create Date: 2026-02-28 01:41:07.027071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ad7cb7b7e9'
down_revision: Union[str, Sequence[str], None] = 'b6f9f417bd0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim_features', sa.Column('submitted_hour', sa.Integer(), nullable=True))
    op.add_column('claim_features', sa.Column('eligibility_checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim_features', 'eligibility_checked')
    op.drop_column('claim_features', 'submitted_hour')
    # ### end Alembic commands ###
