"""initial schema

Revision ID: 91869c8cce95
Revises: 
Create Date: 2026-02-17 00:03:01.007896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91869c8cce95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('training_date', sa.DateTime(), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('national_id_hash', sa.String(length=64), nullable=True),
    sa.Column('sha_number', sa.String(length=50), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('is_deceased', sa.Boolean(), nullable=False),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('iprs_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_patients_national_id_hash'), 'patients', ['national_id_hash'], unique=True)
    op.create_index(op.f('ix_patients_sha_number'), 'patients', ['sha_number'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False),
    sa.Column('provider_id_number', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('sub_county', sa.String(length=100), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('accreditation_status', sa.String(length=50), nullable=True),
    sa.Column('sha_contract_status', sa.String(length=50), nullable=True),
    sa.Column('contract_start_date', sa.DateTime(), nullable=True),
    sa.Column('contract_end_date', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('total_claims_count', sa.Integer(), nullable=False),
    sa.Column('flagged_claims_count', sa.Integer(), nullable=False),
    sa.Column('approved_claims_count', sa.Integer(), nullable=False),
    sa.Column('rejected_claims_count', sa.Integer(), nullable=False),
    sa.Column('total_claims_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('average_claim_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_providers_county'), 'providers', ['county'], unique=False)
    op.create_index(op.f('ix_providers_provider_code'), 'providers', ['provider_code'], unique=True)
    op.create_index(op.f('ix_providers_provider_id_number'), 'providers', ['provider_id_number'], unique=True)
    op.create_table('system_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.DateTime(), nullable=True),
    sa.Column('total_claims', sa.Integer(), nullable=False),
    sa.Column('flagged_claims', sa.Integer(), nullable=False),
    sa.Column('critical_alerts', sa.Integer(), nullable=False),
    sa.Column('auto_approved_claims', sa.Integer(), nullable=False),
    sa.Column('total_claim_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('flagged_claim_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('estimated_fraud_prevented', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('false_positive_rate', sa.Float(), nullable=True),
    sa.Column('false_negative_rate', sa.Float(), nullable=True),
    sa.Column('detection_accuracy', sa.Float(), nullable=True),
    sa.Column('avg_processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('avg_investigation_time_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_metric_date'), 'system_metrics', ['metric_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'INVESTIGATOR', 'ANALYST', name='userrole'), nullable=False),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_on_duty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('patient_national_id', sa.String(length=20), nullable=True),
    sa.Column('patient_sha_number', sa.String(length=50), nullable=True),
    sa.Column('patient_full_name', sa.String(length=255), nullable=True),
    sa.Column('visit_type', sa.Enum('INPATIENT', 'OUTPATIENT', 'DAYCARE', name='visittype'), nullable=True),
    sa.Column('visit_admission_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('op_ip_number', sa.String(length=50), nullable=True),
    sa.Column('is_new_visit', sa.Boolean(), nullable=True),
    sa.Column('admission_diagnosis', sa.Text(), nullable=True),
    sa.Column('admission_diagnosis_codes', sa.JSON(), nullable=True),
    sa.Column('discharge_diagnosis', sa.Text(), nullable=True),
    sa.Column('discharge_diagnosis_codes', sa.JSON(), nullable=True),
    sa.Column('procedures', sa.JSON(), nullable=True),
    sa.Column('rendering_physician_name', sa.String(length=255), nullable=True),
    sa.Column('rendering_physician_reg_no', sa.String(length=50), nullable=True),
    sa.Column('accommodation_type', sa.String(length=100), nullable=True),
    sa.Column('is_referred', sa.Boolean(), nullable=False),
    sa.Column('referring_facility', sa.String(length=255), nullable=True),
    sa.Column('referral_reason', sa.Text(), nullable=True),
    sa.Column('patient_disposition', sa.Enum('IMPROVED', 'RECOVERED', 'LAMA', 'ABSCONDED', 'DIED', name='patientdisposition'), nullable=True),
    sa.Column('referred_to_facility', sa.String(length=255), nullable=True),
    sa.Column('referral_out_reason', sa.Text(), nullable=True),
    sa.Column('claim_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('service_date', sa.DateTime(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('original_file_path', sa.String(length=500), nullable=True),
    sa.Column('original_file_type', sa.String(length=50), nullable=True),
    sa.Column('supporting_documents', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('fraud_flags', sa.JSON(), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'AUTO_APPROVED', 'FLAGGED_REVIEW', 'FLAGGED_CRITICAL', 'APPROVED', 'REJECTED', 'UNDER_INVESTIGATION', name='claimstatus'), nullable=False),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_claims_claim_number'), 'claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_claims_is_flagged'), 'claims', ['is_flagged'], unique=False)
    op.create_index(op.f('ix_claims_patient_national_id'), 'claims', ['patient_national_id'], unique=False)
    op.create_index(op.f('ix_claims_patient_sha_number'), 'claims', ['patient_sha_number'], unique=False)
    op.create_index(op.f('ix_claims_provider_code'), 'claims', ['provider_code'], unique=False)
    op.create_index(op.f('ix_claims_provider_id'), 'claims', ['provider_id'], unique=False)
    op.create_index(op.f('ix_claims_risk_score'), 'claims', ['risk_score'], unique=False)
    op.create_index(op.f('ix_claims_service_date'), 'claims', ['service_date'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_index(op.f('ix_claims_visit_admission_date'), 'claims', ['visit_admission_date'], unique=False)
    op.create_table('fraud_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='fraudseverity'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('detection_module', sa.String(length=50), nullable=True),
    sa.Column('module_confidence', sa.Float(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('is_confirmed_fraud', sa.Boolean(), nullable=True),
    sa.Column('estimated_fraud_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_fraud_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_fraud_alerts_alert_type'), 'fraud_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_severity'), 'fraud_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_status'), 'fraud_alerts', ['status'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('investigator_id', sa.UUID(), nullable=True),
    sa.Column('investigation_number', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('estimated_fraud_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_fraud_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('recovered_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_fraud_confirmed', sa.Boolean(), nullable=True),
    sa.Column('prosecution_recommended', sa.Boolean(), nullable=False),
    sa.Column('administrative_action', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['fraud_alerts.id'], ),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_investigations_investigation_number'), 'investigations', ['investigation_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigations_investigation_number'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_fraud_alerts_status'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_severity'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_alert_type'), table_name='fraud_alerts')
    op.drop_table('fraud_alerts')
    op.drop_index(op.f('ix_claims_visit_admission_date'), table_name='claims')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_service_date'), table_name='claims')
    op.drop_index(op.f('ix_claims_risk_score'), table_name='claims')
    op.drop_index(op.f('ix_claims_provider_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_provider_code'), table_name='claims')
    op.drop_index(op.f('ix_claims_patient_sha_number'), table_name='claims')
    op.drop_index(op.f('ix_claims_patient_national_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_is_flagged'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_number'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_metrics_metric_date'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_providers_provider_id_number'), table_name='providers')
    op.drop_index(op.f('ix_providers_provider_code'), table_name='providers')
    op.drop_index(op.f('ix_providers_county'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_patients_sha_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_national_id_hash'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
