"""add provider bed_capacity

Revision ID: bb1fb610df58
Revises: 88ad7cb7b7e9
Create Date: 2026-03-04 22:59:17.772605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1fb610df58'
down_revision: Union[str, Sequence[str], None] = '88ad7cb7b7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('bed_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'bed_capacity')
    # ### end Alembic commands ###
