"""add facility_level to providers

Revision ID: e36c9a87d037
Revises: ff70692b3b75
Create Date: 2026-03-07 12:21:54.151020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36c9a87d037'
down_revision: Union[str, Sequence[str], None] = 'ff70692b3b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('facility_level', sa.Enum('LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', 'LEVEL_6', name='facility_level_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'facility_level')
    # ### end Alembic commands ###
