"""refactor & add new models

Revision ID: ff4279b4e85f
Revises: 03e7f83d7d80
Create Date: 2026-02-26 21:35:41.698160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff4279b4e85f'
down_revision: Union[str, Sequence[str], None] = '03e7f83d7d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha_member_id', sa.String(length=50), nullable=False, comment='SHA-issued member ID'),
    sa.Column('national_id', sa.String(length=20), nullable=True, comment='Kenya National ID — treat as PII'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_enum'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment='PII — encrypt at rest'),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('coverage_status', sa.String(length=50), nullable=True, comment='ACTIVE / INACTIVE / SUSPENDED'),
    sa.Column('scheme', sa.String(length=100), nullable=True, comment='e.g. Social Health Insurance Fund'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_national_id'), 'members', ['national_id'], unique=False)
    op.create_index(op.f('ix_members_sha_member_id'), 'members', ['sha_member_id'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Permission code, e.g. 'create_case'"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True, comment="'claims' | 'fraud' | 'cases' | 'admin' | 'analytics'"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha_provider_code', sa.String(length=50), nullable=False, comment='Unique provider code assigned by SHA'),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('sub_county', sa.String(length=100), nullable=True),
    sa.Column('facility_type', sa.Enum('PUBLIC_HOSPITAL', 'PRIVATE_HOSPITAL', 'FAITH_BASED', 'CLINIC', 'LABORATORY', 'PHARMACY', 'SPECIALIST_CENTER', name='facility_type_enum'), nullable=True),
    sa.Column('accreditation_status', sa.Enum('ACTIVE', 'SUSPENDED', 'REVOKED', 'PENDING', name='accreditation_status_enum'), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avg_claim_amount', sa.Numeric(precision=14, scale=2), nullable=True, comment='Rolling average claim amount for this provider'),
    sa.Column('peer_avg', sa.Numeric(precision=14, scale=2), nullable=True, comment='Average claim amount for peer providers in same county/type'),
    sa.Column('high_risk_flag', sa.Boolean(), nullable=False, comment='Set to True if provider has been flagged as high-risk'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_accreditation_status'), 'providers', ['accreditation_status'], unique=False)
    op.create_index(op.f('ix_providers_sha_provider_code'), 'providers', ['sha_provider_code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Role name, e.g. 'fraud_analyst'"),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False, comment='System roles cannot be deleted via the UI'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Superuser bypasses all permission checks'),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False, comment='Consecutive failed login attempts — lock account after threshold'),
    sa.Column('locked_until', sa.TIMESTAMP(), nullable=True, comment='Account locked until this datetime after too many failed logins'),
    sa.Column('password_changed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='NULL for system-initiated actions'),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'TOKEN_REFRESHED', 'PASSWORD_CHANGED', 'USER_CREATED', 'USER_UPDATED', 'USER_DEACTIVATED', 'ROLE_ASSIGNED', 'ROLE_REMOVED', 'CLAIM_INGESTED', 'CLAIM_STATUS_UPDATED', 'FEATURES_COMPUTED', 'CLAIM_SCORED', 'SCORE_OVERRIDDEN', 'CASE_CREATED', 'CASE_ASSIGNED', 'CASE_STATUS_UPDATED', 'CASE_NOTE_ADDED', 'CASE_CLOSED', 'RULE_CREATED', 'RULE_UPDATED', 'RULE_TOGGLED', 'MODEL_REGISTERED', 'MODEL_DEPLOYED', name='audit_action_enum'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True, comment="e.g. 'Claim', 'FraudCase', 'User'"),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment='PK of the affected record'),
    sa.Column('audit_log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary context — diff, old/new values, request IP, etc.'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_performed_at', 'audit_logs', ['performed_at'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha_claim_id', sa.String(length=100), nullable=False, comment='SHA-issued claim reference number'),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('claim_type', sa.Enum('INPATIENT', 'OUTPATIENT', 'EMERGENCY', 'MATERNITY', 'DENTAL', 'OPTICAL', name='claim_type_enum'), nullable=True),
    sa.Column('sha_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'FLAGGED', 'PAID', name='claim_status_enum'), nullable=False),
    sa.Column('admission_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discharge_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('diagnosis_codes', postgresql.ARRAY(sa.String()), nullable=True, comment='ICD-10 diagnosis codes — indexed with GIN for fast array search'),
    sa.Column('total_claim_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('approved_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Immutable original claim payload from SHA API'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_claims_diagnosis', 'claims', ['diagnosis_codes'], unique=False, postgresql_using='gin')
    op.create_index('idx_claims_member', 'claims', ['member_id'], unique=False)
    op.create_index('idx_claims_provider', 'claims', ['provider_id'], unique=False)
    op.create_index('idx_claims_status', 'claims', ['sha_status'], unique=False)
    op.create_index('idx_claims_submitted', 'claims', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_claims_claim_type'), 'claims', ['claim_type'], unique=False)
    op.create_index(op.f('ix_claims_sha_claim_id'), 'claims', ['sha_claim_id'], unique=True)
    op.create_index(op.f('ix_claims_sha_status'), 'claims', ['sha_status'], unique=False)
    op.create_table('fraud_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False, comment="Unique machine-readable name, e.g. 'duplicate_claim_7d'"),
    sa.Column('display_name', sa.String(length=200), nullable=True, comment='Human-readable label for the dashboard'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True, comment="'duplicate' | 'upcoding' | 'provider' | 'member' | 'timing'"),
    sa.Column('weight', sa.Numeric(precision=6, scale=4), nullable=False, comment='Score contribution (0-100) when this rule fires'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Rule expression: {"field": "...", "operator": "...", "value": ...}'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_index(op.f('ix_fraud_rules_is_active'), 'fraud_rules', ['is_active'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_name', sa.String(length=100), nullable=False, comment="Human-readable version tag, e.g. 'xgboost-v2.1-2026Q1'"),
    sa.Column('model_type', sa.Enum('XGBOOST', 'LIGHTGBM', 'ISOLATION_FOREST', 'AUTOENCODER', 'LOGISTIC', name='model_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('training_start', sa.Date(), nullable=True),
    sa.Column('training_end', sa.Date(), nullable=True),
    sa.Column('training_sample_size', sa.Integer(), nullable=True, comment='Number of claims used to train this model'),
    sa.Column('model_artifact_path', sa.String(length=500), nullable=True, comment='S3 / MinIO path to the serialised model artifact'),
    sa.Column('performance_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='e.g. {"auc_roc": 0.94, "precision": 0.87, "recall": 0.81, "f1": 0.84}'),
    sa.Column('feature_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Ordered list of feature names the model was trained on'),
    sa.Column('is_deployed', sa.Boolean(), nullable=False, comment='True = this version is actively used for scoring'),
    sa.Column('deployed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deployed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['deployed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_name')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='SHA-256 hash of the raw refresh token — never store the raw value'),
    sa.Column('token_type', sa.Enum('ACCESS', 'REFRESH', name='token_type_enum'), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_table('claim_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('provider_avg_cost_90d', sa.Numeric(precision=14, scale=2), nullable=True, comment="Provider's average claim cost over trailing 90 days"),
    sa.Column('provider_cost_zscore', sa.Numeric(precision=10, scale=4), nullable=True, comment="Z-score of this claim's cost vs provider's historical distribution"),
    sa.Column('member_visits_30d', sa.Integer(), nullable=True, comment='Number of facility visits by this member in last 30 days'),
    sa.Column('member_visits_7d', sa.Integer(), nullable=True, comment='Number of facility visits by this member in last 7 days'),
    sa.Column('member_unique_providers_30d', sa.Integer(), nullable=True, comment='Number of distinct providers visited by member in last 30 days (hopping flag)'),
    sa.Column('duplicate_within_7d', sa.Boolean(), nullable=True, comment='True if same member + similar diagnosis submitted within 7 days'),
    sa.Column('length_of_stay', sa.Integer(), nullable=True, comment='Admission to discharge in days (0 for outpatient)'),
    sa.Column('weekend_submission', sa.Boolean(), nullable=True, comment='True if claim was submitted on a Saturday or Sunday'),
    sa.Column('diagnosis_cost_zscore', sa.Numeric(precision=10, scale=4), nullable=True, comment="Z-score of this claim's cost vs national avg for same ICD-10 diagnosis"),
    sa.Column('service_count', sa.Integer(), nullable=True, comment='Total number of service line items in this claim'),
    sa.Column('has_lab_without_diagnosis', sa.Boolean(), nullable=True, comment='True if lab tests billed but no supporting diagnosis code present'),
    sa.Column('has_surgery_without_theatre', sa.Boolean(), nullable=True, comment='True if surgery billed but no theatre notes attached'),
    sa.Column('engineered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id')
    )
    op.create_table('claim_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('service_code', sa.String(length=100), nullable=True, comment='SHA / NHIF service billing code'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_upcoded', sa.Boolean(), nullable=False, comment='Set True by UpcodingDetector if service code is inflated'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_services_claim_id'), 'claim_services', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_services_service_code'), 'claim_services', ['service_code'], unique=False)
    op.create_table('fraud_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True, comment='Which ML model version produced this score'),
    sa.Column('rule_score', sa.Numeric(precision=6, scale=4), nullable=True, comment='Score from deterministic rule engine (0-100)'),
    sa.Column('ml_probability', sa.Numeric(precision=6, scale=4), nullable=True, comment='ML model fraud probability scaled to 0-100'),
    sa.Column('anomaly_score', sa.Numeric(precision=6, scale=4), nullable=True, comment='Isolation Forest / autoencoder anomaly score (0-100)'),
    sa.Column('detector_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Dict of detector name → score, e.g. {"DuplicateDetector": 75.0}'),
    sa.Column('final_score', sa.Numeric(precision=6, scale=4), nullable=True, comment='Weighted aggregate: rule×0.4 + ml×0.4 + avg_detector×0.2'),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level_enum'), nullable=True, comment='LOW / MEDIUM / HIGH / CRITICAL'),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scored_by', sa.String(length=100), nullable=True, comment="'system' for auto-score, user email for manual override"),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_scores_claim_id'), 'fraud_scores', ['claim_id'], unique=False)
    op.create_index(op.f('ix_fraud_scores_risk_level'), 'fraud_scores', ['risk_level'], unique=False)
    op.create_table('fraud_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('fraud_score_id', sa.UUID(), nullable=False, comment='The scoring event that triggered this case'),
    sa.Column('assigned_to', sa.UUID(), nullable=True, comment='Fraud analyst responsible for this case'),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'CONFIRMED_FRAUD', 'CLEARED', 'CLOSED', name='case_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='case_priority_enum'), nullable=False),
    sa.Column('resolution_summary', sa.Text(), nullable=True, comment="Analyst's summary when closing the case"),
    sa.Column('estimated_loss', sa.Numeric(precision=14, scale=2), nullable=True, comment='Estimated financial loss if confirmed fraud'),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['fraud_score_id'], ['fraud_scores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', name='uq_fraud_cases_claim')
    )
    op.create_index(op.f('ix_fraud_cases_claim_id'), 'fraud_cases', ['claim_id'], unique=False)
    op.create_index(op.f('ix_fraud_cases_status'), 'fraud_cases', ['status'], unique=False)
    op.create_table('fraud_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fraud_score_id', sa.UUID(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False, comment="Human-readable explanation, e.g. 'provider_cost_zscore exceeded 3σ threshold'"),
    sa.Column('feature_name', sa.String(length=100), nullable=True, comment="Machine-readable feature key, e.g. 'duplicate_within_7d'"),
    sa.Column('feature_value', sa.String(length=200), nullable=True, comment='Actual value that triggered this explanation'),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=True, comment='SHAP value or rule weight contributing to the final score'),
    sa.Column('source', sa.String(length=50), nullable=True, comment="'rule_engine', 'ml_model', 'DuplicateDetector', 'ProviderProfiler', etc."),
    sa.ForeignKeyConstraint(['fraud_score_id'], ['fraud_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_explanations_fraud_score_id'), 'fraud_explanations', ['fraud_score_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of attachment metadata, e.g. [{"name": "discharge_summary.pdf", "url": "..."}]'),
    sa.ForeignKeyConstraint(['case_id'], ['fraud_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_table('fraud_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False, comment='The claim that triggered this alert'),
    sa.Column('fraud_score_id', sa.UUID(), nullable=True, comment='The specific scoring event that produced this alert (if score-triggered)'),
    sa.Column('fraud_case_id', sa.UUID(), nullable=True, comment='Set when this alert is escalated to a full investigation case'),
    sa.Column('alert_type', sa.Enum('HIGH_RISK_SCORE', 'CRITICAL_RISK_SCORE', 'DUPLICATE_CLAIM', 'PHANTOM_PATIENT', 'UPCODING_DETECTED', 'PROVIDER_ANOMALY', 'RULE_THRESHOLD_BREACH', 'MEMBER_FREQUENCY_ABUSE', 'PROVIDER_CLAIM_SPIKE', 'LATE_NIGHT_SUBMISSION', 'BULK_SUBMISSION', 'MODEL_CONFIDENCE_LOW', 'RESUBMISSION_PATTERN', name='alert_type_enum'), nullable=False, comment='What kind of fraud signal triggered this alert'),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'HIGH', 'CRITICAL', name='alert_severity_enum'), nullable=False, comment='Operational urgency level'),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'ESCALATED', 'RESOLVED', 'EXPIRED', name='alert_status_enum'), nullable=False, comment='Current lifecycle state of this alert'),
    sa.Column('title', sa.String(length=255), nullable=False, comment="Short human-readable headline, e.g. 'Duplicate claim detected within 5 days'"),
    sa.Column('message', sa.Text(), nullable=False, comment='Full alert description with context for the analyst'),
    sa.Column('triggered_by', sa.String(length=100), nullable=True, comment="Component that raised this alert, e.g. 'DuplicateDetector', 'RuleEngine', 'MLModel'"),
    sa.Column('score_at_alert', sa.Numeric(precision=6, scale=4), nullable=True, comment='The final_score value when this alert was raised'),
    sa.Column('assigned_to', sa.UUID(), nullable=True, comment='Analyst this alert is routed to (NULL = unassigned)'),
    sa.Column('auto_escalate', sa.Boolean(), nullable=False, comment='If True, system will auto-create a FraudCase if alert is unacknowledged past deadline'),
    sa.Column('auto_escalate_after_hours', sa.Integer(), nullable=True, comment='Hours after raised_at before auto-escalation triggers (e.g. 24)'),
    sa.Column('escalated_at', sa.TIMESTAMP(), nullable=True, comment='Timestamp when this alert was escalated to a FraudCase'),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True, comment='Alert auto-expires (status → EXPIRED) after this time if unactioned'),
    sa.Column('resolved_by', sa.UUID(), nullable=True, comment='Analyst who resolved or dismissed this alert'),
    sa.Column('resolution_note', sa.Text(), nullable=True, comment='Optional note recorded when resolving or dismissing the alert'),
    sa.Column('is_false_positive', sa.Boolean(), nullable=True, comment='Set True if analyst marks this as a false positive (used for model feedback)'),
    sa.Column('fraud_alert_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary context payload from the triggering detector, e.g. {"duplicate_claim_ids": ["abc", "def"], "days_between": 3}'),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fraud_case_id'], ['fraud_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fraud_score_id'], ['fraud_scores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_alert_type', 'fraud_alerts', ['alert_type'], unique=False)
    op.create_index('idx_alerts_assigned', 'fraud_alerts', ['assigned_to'], unique=False)
    op.create_index('idx_alerts_claim', 'fraud_alerts', ['claim_id'], unique=False)
    op.create_index('idx_alerts_raised_at', 'fraud_alerts', ['raised_at'], unique=False)
    op.create_index('idx_alerts_severity', 'fraud_alerts', ['severity'], unique=False)
    op.create_index('idx_alerts_status', 'fraud_alerts', ['status'], unique=False)
    op.create_table('alert_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('DASHBOARD', 'EMAIL', 'SMS', 'WEBHOOK', 'SLACK', name='alert_channel_enum'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=True, comment='Email address, phone number, webhook URL, or Slack channel'),
    sa.Column('delivery_status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'SKIPPED', name='delivery_status_enum'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False, comment='Number of delivery attempts made'),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True, comment='HTTP response code for webhook deliveries'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error detail if delivery failed'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Request body sent to the channel endpoint'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['fraud_alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_alert', 'alert_notifications', ['alert_id'], unique=False)
    op.create_index('idx_notif_channel', 'alert_notifications', ['channel'], unique=False)
    op.create_index('idx_notif_status', 'alert_notifications', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_alert_notifications_delivery_status'), 'alert_notifications', ['delivery_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_notifications_delivery_status'), table_name='alert_notifications')
    op.drop_index('idx_notif_status', table_name='alert_notifications')
    op.drop_index('idx_notif_channel', table_name='alert_notifications')
    op.drop_index('idx_notif_alert', table_name='alert_notifications')
    op.drop_table('alert_notifications')
    op.drop_index('idx_alerts_status', table_name='fraud_alerts')
    op.drop_index('idx_alerts_severity', table_name='fraud_alerts')
    op.drop_index('idx_alerts_raised_at', table_name='fraud_alerts')
    op.drop_index('idx_alerts_claim', table_name='fraud_alerts')
    op.drop_index('idx_alerts_assigned', table_name='fraud_alerts')
    op.drop_index('idx_alerts_alert_type', table_name='fraud_alerts')
    op.drop_table('fraud_alerts')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_fraud_explanations_fraud_score_id'), table_name='fraud_explanations')
    op.drop_table('fraud_explanations')
    op.drop_index(op.f('ix_fraud_cases_status'), table_name='fraud_cases')
    op.drop_index(op.f('ix_fraud_cases_claim_id'), table_name='fraud_cases')
    op.drop_table('fraud_cases')
    op.drop_index(op.f('ix_fraud_scores_risk_level'), table_name='fraud_scores')
    op.drop_index(op.f('ix_fraud_scores_claim_id'), table_name='fraud_scores')
    op.drop_table('fraud_scores')
    op.drop_index(op.f('ix_claim_services_service_code'), table_name='claim_services')
    op.drop_index(op.f('ix_claim_services_claim_id'), table_name='claim_services')
    op.drop_table('claim_services')
    op.drop_table('claim_features')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_fraud_rules_is_active'), table_name='fraud_rules')
    op.drop_table('fraud_rules')
    op.drop_index(op.f('ix_claims_sha_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_sha_claim_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_type'), table_name='claims')
    op.drop_index('idx_claims_submitted', table_name='claims')
    op.drop_index('idx_claims_status', table_name='claims')
    op.drop_index('idx_claims_provider', table_name='claims')
    op.drop_index('idx_claims_member', table_name='claims')
    op.drop_index('idx_claims_diagnosis', table_name='claims', postgresql_using='gin')
    op.drop_table('claims')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_performed_at', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_providers_sha_provider_code'), table_name='providers')
    op.drop_index(op.f('ix_providers_accreditation_status'), table_name='providers')
    op.drop_table('providers')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_members_sha_member_id'), table_name='members')
    op.drop_index(op.f('ix_members_national_id'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
