"""add department to users

Revision ID: ff70692b3b75
Revises: 30f15b2003b4
Create Date: 2026-03-05 14:22:03.980092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff70692b3b75'
down_revision: Union[str, Sequence[str], None] = '30f15b2003b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True, comment="e.g. 'Fraud Investigation', 'Data Science', 'Compliance'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
